### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by shaicoleman** [ajporterfield/activejob_dj_overrides#2]
Please add a license, preferably the MIT one (same as DelayedJob and ActiveJob)
https://choosealicense.com/licenses/mit/

**Comment by DavidMikeSimon** [comment]
Seconding this; I'd love to use this gem at my job, but we can't use source libraries that have no license, since technically we could get dinged later on for copyright.

**Comment by ajporterfield** [comment]
@shaicoleman @DavidMikeSimon I just committed an MIT license to the repo.

**Comment by shaicoleman** [comment]
Thanks!
